services:
  db:
    image: postgres:alpine
    env_file: .env
    environment:
      POSTGRES_USER: tuna_user
      POSTGRES_PASSWORD: sifre123
      POSTGRES_DB: task_db
    ports:
      - "5432:5432" # pgAdmin ile dışarıdan bağlanmak istersen diye
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Düzeltildi: Klasör değil dosya yolu
       
  app:
    build: .
    env_file: .env
    ports:
      - "5000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://tuna_user:sifre123@db:5432/task_db?sslmode=disable

volumes: # Burası kritik: Volume tanımlarını buraya eklemelisin
  postgres_data: